name = "stellara/contracts"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'stellara/contracts'"

[repository]
user = "stellara"
project = "contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.0.0"
source = "github"

[config]
